### ISSUE TITLE
Support wp_cache_get_multiple

### ISSUE THREAD

**Issue by bueltge** [inpsyde/WP-Stash#18]
Available since WP 5.5, see https://make.wordpress.org/core/2020/08/11/introduce-wp_cache_get_multiple/

**Comment by Biont** [comment]
We can implement this, but it needs to be stated that won't make a practical difference: WP Core provides a fallback shim that simply wraps multiple `wp_cache_get` calls. And guess what: [Stash does the same thing!](https://github.com/tedious/Stash/blob/8f1d28c765b257b05e932c28ad75c809e34fe12c/src/Stash/Pool.php#L138-L149)

It is still a good idea to support this so that we are forward compatible in the event that Stash adds support for this, but I don't see that happening soon. I could not even find an open issue for this apart from [this seven-year old issue](https://github.com/tedious/Stash/issues/40)

**Comment by bueltge** [comment]
So we should leave it for now, maybe StashPHP will support it later, and then is the effort helpful.

**Comment by Biont** [comment]
It doesn't take much effort to do it now and allowed me to do some welcome house cleaning

**Comment by bueltge** [comment]
So feel free to do them. However, I understand that the benefit of this function is less. But housekeeping is more helpful. ;)
