### ISSUE TITLE
[Feature Request]: Implement new core caching api functions.

### ISSUE THREAD

**Issue by spacedmonkey** [inpsyde/WP-Stash#28]
### Is your feature request related to a problem?

There has been a number of improve to the caching api, including. Adding the following functions. 

- wp_cache_flush_runtime
- wp_cache_add_multiple
- wp_cache_set_multiple
- wp_cache_delete_multiple
- wp_cache_flush_group
- wp_cache_supports

### Describe the desired solution

Implement core functions. 

### Describe the alternatives that you have considered

N / A

### Additional context

https://make.wordpress.org/core/2022/04/29/caching-improvements-in-wordpress-6-0/
https://make.wordpress.org/core/2022/10/11/performance-field-guide-for-wordpress-6-1/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Biont** [comment]
Hello @spacedmonkey and thank you for raising this.
This is definitely something worth picking up and we'll try to allocate some time soon.

It should be noted that the `*_multiple` are unlikely to yield any improvements, because the underlying StashPHP library itself only [unwraps these calls back into single-item operations](https://github.com/tedious/Stash/blob/a2c9df16c77b13e1f90462f30597a772166eea8f/src/Stash/Pool.php#L209-L218)
(See also #18 for reference)

There is still value in implementing them for future-proofing, though

**Comment by spacedmonkey** [comment]
Thanks @Biont 

The biggest one of this list I would like to see implemented is `wp_cache_supports`. I am core committer and it is extremely useful to understand what feature your object cache supports. Specially group flush and multiple gets. We can't use these features in core unless we know they are supported. 

See https://github.com/WordPress/performance/issues/718 for more context.

**Comment by Biont** [comment]
https://github.com/inpsyde/WP-Stash/releases/tag/v3.4.0 @spacedmonkey
